export const CATEGORIES = [
  { id: 'all', slug: 'all', name: 'All', count: 11 },
  { id: 'fat-loss', slug: 'fat-loss', name: 'Fat Loss', count: 3 },
  { id: 'muscle-growth', slug: 'muscle-growth', name: 'Muscle Growth', count: 6 },
  { id: 'recovery', slug: 'recovery', name: 'Recovery', count: 2 },
];

export const PRODUCTS = [
  {
    id: 'bpc-157',
    name: 'BPC-157 – 5mg',
    slug: 'bpc-157',
    category: 'recovery',
    category_name: 'Recovery',
    price: 49.99,
    image_url: '/images/bpc-157-300x300.webp',
    featured: true,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 99%',
    form: 'Lyophilized',
    stock: 100,
    in_stock: true,
    short_desc: 'Widely studied peptide for tissue repair research.',
    description: 'BPC-157 (Body Protection Compound-157) is a pentadecapeptide composed of 15 amino acids derived from human gastric juice protein.',
  },
  {
    id: 'cjc-1295-no-dac',
    name: 'CJC-1295 (No DAC) – 2mg',
    slug: 'cjc-1295-no-dac',
    category: 'muscle-growth',
    category_name: 'Muscle Growth',
    price: 42.95,
    image_url: '/images/1295-300x300.webp',
    featured: false,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 98%',
    form: 'Lyophilized',
    stock: 85,
    in_stock: true,
    short_desc: 'GHRH analog studied for growth-hormone research.',
    description: 'CJC-1295 without DAC is a synthetic analog of growth hormone-releasing hormone (GHRH) designed to stimulate GH secretion.',
  },
  {
    id: 'cjc-1295-with-dac',
    name: 'CJC-1295 with DAC – 2mg',
    slug: 'cjc-1295-with-dac',
    category: 'muscle-growth',
    category_name: 'Muscle Growth',
    price: 47.95,
    image_url: '/images/cjc-1295-with-dac-300x300.webp',
    featured: false,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 99%',
    form: 'Lyophilized',
    stock: 70,
    in_stock: true,
    short_desc: 'Long-acting GHRH analog for research use.',
    description: 'CJC-1295 with Drug Affinity Complex (DAC) provides extended half-life for biostability in laboratory investigations.',
  },
  {
    id: 'follistatin',
    name: 'Follistatin',
    slug: 'follistatin',
    category: 'muscle-growth',
    category_name: 'Muscle Growth',
    price: 149.95,
    image_url: '/images/follistatin-1-300x300.webp',
    featured: true,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 99%',
    form: 'Lyophilized',
    stock: 50,
    in_stock: true,
    short_desc: 'Research peptide studied for muscle-related pathways.',
    description: 'Follistatin is an autocrine glycoprotein that is potent at inhibiting myostatin signaling in muscle cellular research.',
  },
  {
    id: 'frag-176-191',
    name: 'FRAG (176-191)',
    slug: 'frag-176-191',
    category: 'fat-loss',
    category_name: 'Fat Loss',
    price: 34.95,
    image_url: '/images/fragment-1-300x300.webp',
    featured: false,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 99%',
    form: 'Lyophilized',
    stock: 120,
    in_stock: true,
    short_desc: 'Fragment peptide studied in fat-metabolism research.',
    description: 'A modified form of amino acids 176-191 of human growth hormone, specifically studied for lipolysis mechanisms.',
  },
  {
    id: 'ftpp',
    name: 'FTPP',
    slug: 'ftpp',
    category: 'fat-loss',
    category_name: 'Fat Loss',
    price: 99.95,
    image_url: '/images/FTTP-300x300.webp',
    featured: false,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 99%',
    form: 'Lyophilized',
    stock: 65,
    in_stock: true,
    short_desc: 'Peptide studied for fat-loss related pathways.',
    description: 'Adipotide (FTPP) is an experimental proapoptotic peptide studied for targeting vascular supply of white adipose tissue.',
  },
  {
    id: 'ghrp-2',
    name: 'GHRP-2',
    slug: 'ghrp-2',
    category: 'muscle-growth',
    category_name: 'Muscle Growth',
    price: 24.95,
    image_url: '/images/GHRP-2-300x300.webp',
    featured: false,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 98%',
    form: 'Lyophilized',
    stock: 95,
    in_stock: true,
    short_desc: 'Growth-hormone-releasing peptide for research use.',
    description: 'Growth Hormone Releasing Peptide-2 is a synthetic hexapeptide that binds to the ghrelin/growth hormone secretagogue receptor.',
  },
  {
    id: 'igf-1-lr3',
    name: 'IGF-1 LR3',
    slug: 'igf-1-lr3',
    category: 'muscle-growth',
    category_name: 'Muscle Growth',
    price: 69.95,
    image_url: '/images/igf-1lr3-300x300.webp',
    featured: false,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 99%',
    form: 'Lyophilized',
    stock: 80,
    in_stock: true,
    short_desc: 'Long-acting IGF-1 analog for research use.',
    description: 'Long R3 IGF-1 is an 83 amino acid analog of IGF-1 comprising the complete human IGF-1 sequence with substitution of an Arg for Glu at position 3.',
  },
  {
    id: 'peg-mgf',
    name: 'PEG MGF – 2mg',
    slug: 'peg-mgf',
    category: 'muscle-growth',
    category_name: 'Muscle Growth',
    price: 47.95,
    image_url: '/images/PEG-MGF-1-300x300.webp',
    featured: false,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 99%',
    form: 'Lyophilized',
    stock: 75,
    in_stock: true,
    short_desc: 'Modified growth factor peptide for muscle research.',
    description: 'Pegylated Mechano Growth Factor is a splice variant of IGF-1 combined with polyethylene glycol to increase biological half-life.',
  },
  {
    id: 'retatrutide',
    name: 'Retatrutide',
    slug: 'retatrutide',
    category: 'fat-loss',
    category_name: 'Fat Loss',
    price: 179.95,
    image_url: '/images/retatrutide-300x300.webp',
    featured: false,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 99%',
    form: 'Lyophilized',
    stock: 45,
    in_stock: true,
    short_desc: 'Multi-agonist peptide studied in metabolic research.',
    description: 'Retatrutide is a triple hormone receptor agonist targeting GIP, GLP-1, and glucagon receptors for metabolic pathways.',
  },
  {
    id: 'tb-500',
    name: 'TB-500 (Thymosin Beta-4) – 5mg',
    slug: 'tb-500',
    category: 'recovery',
    category_name: 'Recovery',
    price: 38.95,
    image_url: '/images/tb-500-2-300x300.webp',
    featured: false,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 98%',
    form: 'Lyophilized',
    stock: 110,
    in_stock: true,
    short_desc: 'Peptide studied for tissue repair and recovery research.',
    description: 'TB-500 is a synthetic fraction of the naturally occurring peptide Thymosin Beta-4, studied for actin regulation and cellular migration.',
  },
];
